import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Orbitron } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} antialiased bm-root`}>
        {/* Ambient UI overlays */}
        <div className="bm-grid" />
        <div className="bm-scanlines" />
        <div className="bm-noise" />
        <div className="bm-vignette" />
        {/* Surreal aurora blobs */}
        <div className="aurora-wrap">
          <div className="aurora a1" />
          <div className="aurora a2" />
        </div>
        <div className="relative z-10">{children}</div>
      </body>
    </html>
  );
}
